CREATE DATABASE EMP_DB;
USE EMP_DB;

CREATE TABLE REGIONS(REGION_ID INT NOT NULL, REGION_NAME VARCHAR(20));
CREATE TABLE COUNTRIES(COUNTRY_ID VARCHAR(2) NOT NULL, COUNTRY_NAME VARCHAR (60), REGION_ID INT);
CREATE TABLE LOCATIONS(LOCATION_ID INT, STREET_ADDRESS VARCHAR(40), POSTAL_CODE VARCHAR(15), CITY VARCHAR(30) NOT NULL,STATE_PROVINCE VARCHAR(25),COUNTRY_ID VARCHAR(2));
CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INT, DEPARTMENT_NAME VARCHAR(20) NOT NULL,MANAGER_ID INT,LOCATION_ID INT);
CREATE TABLE JOBS(JOB_ID VARCHAR(10), JOB_TITLE VARCHAR(40) NOT NULL,MIN_SALARY INT, MAX_SALARY INT);
CREATE TABLE EMPLOYEES (EMPLOYEE_ID INT,FIRST_NAME VARCHAR(20),LAST_NAME VARCHAR (25) NOT NULL,EMAIL VARCHAR(30) NOT NULL,PHONE_NUMBER VARCHAR(20),HIRE_DATE DATE NOT NULL,JOB_ID VARCHAR(10) NOT NULL,SALARY DOUBLE(8,2),COMMISSION_PCT DOUBLE(2,2),MANAGER_ID INT,DEPARTMENT_ID INT);
CREATE TABLE JOB_HISTORY (EMPLOYEE_ID INT NOT NULL,START_DATE DATE NOT NULL, END_DATE DATE NOT NULL, JOB_ID VARCHAR(10) NOT NULL,DEPARTMENT INT);

SELECT * FROM REGIONS;
ALTER TABLE REGIONS ADD COLUMN REG_CODE CHAR(20);
ALTER TABLE REGIONS MODIFY COLUMN REG_CODE CHAR(7);
ALTER TABLE REGIONS MODIFY COLUMN REG_CODE VARCHAR(7);
ALTER TABLE REGIONS RENAME COLUMN REG_CODE TO REGION_CODE;
ALTER TABLE REGIONS DROP COLUMN REGION_CODE;

RENAME TABLE EMP_REG TO REGIONS;

TRUNCATE TABLE REGIONS;
DROP TABLE REGIONS;