USE EMPLOYEES_DB;

SELECT * FROM EMPLOYEES GROUP BY JOB_ID;
SELECT DEPARTMENT_ID,COUNT(JOB_ID) JOBID FROM EMPLOYEES WHERE DEPARTMENT_ID <= 50 GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID , COUNT(EMPLOYEE_ID) NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, SUM(SALARY) TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, AVG(SALARY) AVERAGE_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, MAX(SALARY) MAXIMUM_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, MIN(SALARY) MINIMUM_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT JOB_ID, COUNT(EMPLOYEE_ID) NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY JOB_ID;
SELECT JOB_ID, SUM(SALARY) TOTAL_SALARY FROM EMPLOYEES GROUP BY JOB_ID;
SELECT JOB_ID, AVG(SALARY) AVERAGE_SALARY FROM EMPLOYEES GROUP BY JOB_ID;
SELECT YEAR(HIRE_DATE) , COUNT(EMPLOYEE_ID) NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE);
SELECT DEPARTMENT_ID , COUNT(EMPLOYEE_ID) NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID)>5;
SELECT JOB_ID, AVG(SALARY) AVERAGE_SALARY FROM EMPLOYEES GROUP BY JOB_ID HAVING AVG(SALARY) > 8000;
SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING SUM(SALARY) > 50000;
SELECT MANAGER_ID , COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY MANAGER_ID HAVING COUNT(EMPLOYEE_ID) >3;
SELECT DEPARTMENT_ID , MAX(SALARY) MAXIMUM_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MAX(SALARY) > 10000;
SELECT DEPARTMENT_ID, JOB_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID;
SELECT DEPARTMENT_ID, JOB_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID;
SELECT DEPARTMENT_ID, YEAR(HIRE_DATE) , SUM(SALARY) TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID, (HIRE_DATE);
SELECT DEPARTMENT_ID, MANAGER_ID, COUNT(EMPLOYEE_ID) NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID, MANAGER_ID;
SELECT DEPARTMENT_ID, JOB_ID, MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, MANAGER_ID, COUNT(EMPLOYEE_ID) NO_OF_EMPLOYEE FROM EMPLOYEES GROUP BY DEPARTMENT_ID, MANAGER_ID;
SELECT DEPARTMENT_ID, JOB_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID;
SELECT YEAR(HIRE_DATE),MONTH(HIRE_DATE), COUNT(EMPLOYEE_ID) NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE),MONTH(HIRE_DATE) ORDER BY NO_OF_EMPLOYEES DESC LIMIT 5;

SELECT YEAR(HIRE_DATE) HIRE_YEAR, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE);
SELECT MONTH(HIRE_DATE) , COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY MONTH(HIRE_DATE);
SELECT YEAR(HIRE_DATE), MONTH(HIRE_DATE),COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY MONTH(HIRE_DATE),YEAR(HIRE_DATE);
SELECT DATE(HIRE_DATE), MONTH(HIRE_DATE),COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DATE(HIRE_DATE), MONTH(HIRE_DATE);
SELECT DATE(HIRE_DATE) ,COUNT(EMPLOYEE_ID)FROM EMPLOYEES GROUP BY DATE(HIRE_DATE);
SELECT DATE(HIRE_DATE), JOB_ID ,COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DATE(HIRE_DATE), JOB_ID;
SELECT DATE(HIRE_DATE), COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DATE(HIRE_DATE) ORDER BY DATE(HIRE_DATE) DESC LIMIT 1;
SELECT DATE(HIRE_DATE),COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DATE(HIRE_DATE) ORDER BY DATE(HIRE_DATE) ASC LIMIT 1;
SELECT YEAR(HIRE_DATE), COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE) ORDER BY  COUNT(EMPLOYEE_ID) DESC LIMIT 1;
SELECT YEAR(HIRE_DATE), COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY MAX(EMPLOYEE_ID);
SELECT YEAR(HIRE_DATE), SUM(SALARY) FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE);
SELECT MONTH(HIRE_DATE),SUM(SALARY) FROM EMPLOYEES GROUP BY MONTH(HIRE_DATE) ORDER BY MONTH(HIRE_DATE) ASC;
SELECT YEAR(HIRE_DATE), DEPARTMENT_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE) , DEPARTMENT_ID;
SELECT YEAR(HIRE_DATE) HIRE_YEAR, JOB_ID,COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE), JOB_ID;
SELECT YEAR(HIRE_DATE) HIRE_YEAR, JOB_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE),JOB_ID;
SELECT YEAR(HIRE_DATE) HIRE_YEAR, MAX(SALARY) FROM EMPLOYEES GROUP BY YEAR(HIRE_DATE);
SELECT EXTRACT(QUARTER FROM HIRE_DATE) QUARTERYEAR, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY QUARTERYEAR;